### data
train_dataset_type: messages
train_dataset_path: tests/fixtures/dummy/sft-vl/thinking_safety_demo.jsonl
train_dataset_prob: "1.0"
max_seq_len: 32768
packing: true
mix_strategy: concat
template_backend: custom
template: ernie_vl
random_shuffle: false

### model
model_name_or_path: baidu/ERNIE-4.5-VL-28B-A3B-Thinking
_attn_implementation: flashmask

### finetuning
# base
stage: VL-SFT
fine_tuning: full
seed: 23
do_train: true
do_eval: false
per_device_train_batch_size: 1
num_train_epochs: 3
max_steps: -1
save_steps: 10000
save_strategy: steps
logging_steps: 1
gradient_accumulation_steps: 2
logging_dir: ./vdl_log
output_dir: ./checkpoints/ernie-vl
disable_tqdm: true

# train
warmup_steps: 0
learning_rate: 1.0e-5

# performance
tensor_model_parallel_size: 4
pipeline_model_parallel_size: 2
sharding: stage1
use_sparse_head_and_loss_fn: true
bf16: true
fp16_opt_level: O2
save_checkpoint_format: "flex_checkpoint"
load_checkpoint_format: "flex_checkpoint"
load_via_cpu: true
freeze_config: freeze_vision

# recompute
recompute: true
recompute_granularity: full
recompute_method: uniform
recompute_num_layers: 1
recompute_modules: ["loss_fn"]
recompute_use_reentrant: true

sequence_parallel: true
pp_seg_method: layer:Ernie4_5_DecoderLayer|ErnieDecoderLayer|EmptyLayer
offload_queue: true
overlap_p2p_comm: true
best_unbalanced_scheduler: true
sharding_comm_buffer_size_MB: 2048
save_sharding_stage1_model_include_freeze_params: true
tensorwise_offload_optimizer: true
unified_checkpoint_config: ignore_merge_optimizer
pre_alloc_memory: 0
amp_master_grad: 1